package com.ppx.mall.bean;

/**
 * cart
 * 
 * @author bianj
 * @version 1.0.0 2021-11-17
 */
public class Cart implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3950508397095475813L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Long id;

    private Long productId;

    private String name;

    private String imgSrc;

    private Double price;

    private Integer count;

    private Double cost;

    private String account;

    private String title;

    /* This code was generated by TableGo tools, mark 1 end. */

    public Cart(Long id, Long productId, String name, String imgSrc, Double price, Integer count, Double cost, String account) {
        this.id = id;
        this.productId = productId;
        this.name = name;
        this.imgSrc = imgSrc;
        this.price = price;
        this.count = count;
        this.cost = cost;
        this.account = account;
    }

    public Cart() {
    }
    /* This code was generated by TableGo tools, mark 2 begin. */

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return this.productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImgSrc() {
        return this.imgSrc;
    }

    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Double getCost() {
        return this.cost;
    }

    public void setCost(Double cost) {
        this.cost = cost;
    }

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public void setTitle(String title){
        this.title=title;
    }

    public String getTitle(){
        return this.title;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "Cart{" +
                "id=" + id +
                ", productId=" + productId +
                ", name='" + name + '\'' +
                ", imgSrc='" + imgSrc + '\'' +
                ", price=" + price +
                ", count=" + count +
                ", cost=" + cost +
                ", account='" + account + '\'' +
                '}';
    }
}