package com.ppx.mall.bean;

import java.time.LocalDateTime;
import java.util.Date;

/**
 * comment
 * 
 * @author bianj
 * @version 1.0.0 2021-11-29
 */
public class Comment implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3741828096389653184L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Long id;

    private Long productId;

    private String account;

    private String content;

    private Long time;

    private Integer type;

    private Integer thumb;

    private Long responseId;

    private Long responseTwoId;

    public Comment(Long id, Long productId, String account, String content, Long time, Integer type, Integer thumb, Long responseId, Long responseTwoId) {
        this.id = id;
        this.productId = productId;
        this.account = account;
        this.content = content;
        this.time = time;
        this.type = type;
        this.thumb = thumb;
        this.responseId = responseId;
        this.responseTwoId = responseTwoId;
    }

    public Comment() {
    }
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getThumb() {
        return thumb;
    }

    public void setThumb(Integer thumb) {
        this.thumb = thumb;
    }

    public Long getResponseId() {
        return responseId;
    }

    public void setResponseId(Long responseId) {
        this.responseId = responseId;
    }

    public Long getResponseTwoId() {
        return responseTwoId;
    }

    public void setResponseTwoId(Long responseTwoId) {
        this.responseTwoId = responseTwoId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "Comment{" +
                "id=" + id +
                ", productId=" + productId +
                ", account='" + account + '\'' +
                ", content='" + content + '\'' +
                ", time=" + time +
                ", type=" + type +
                ", thumb=" + thumb +
                ", responseId=" + responseId +
                ", responseTwoId='" + responseTwoId + '\'' +
                '}';
    }
}