package com.ppx.mall.bean;

/**
 * product_title
 * 
 * @author bianj
 * @version 1.0.0 2021-10-02
 */
public class ProductTitle implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4731113831140694073L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Integer id;

    private String title;

    public ProductTitle(Integer id, String title) {
        this.id = id;
        this.title = title;
    }

    public ProductTitle() {
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "ProductTitle{" +
                "id=" + id +
                ", title='" + title + '\'' +
                '}';
    }
}