package com.ppx.mall.bean;

import java.util.List;

/**
 * product
 * 
 * @author bianj
 * @version 1.0.0 2021-10-02
 */
public class Product implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6382670638269907627L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Long id;

    private Integer titleId;

    private String name;

    private String curPrice;

    private String oriPrice;

    private String description;

    private String imgSrc;

    private String saleDesc;

    private List<ProductImg> imgDetails;

    public Product(Long id, Integer titleId, String name, String curPrice, String oriPrice, String description, String imgSrc,String saleDesc) {
        this.id = id;
        this.titleId = titleId;
        this.name = name;
        this.curPrice = curPrice;
        this.oriPrice = oriPrice;
        this.description = description;
        this.imgSrc = imgSrc;
        this.saleDesc=saleDesc;
    }

    public Product() {
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTitleId() {
        return this.titleId;
    }

    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCurPrice() {
        return this.curPrice;
    }

    public void setCurPrice(String curPrice) {
        this.curPrice = curPrice;
    }

    public String getOriPrice() {
        return this.oriPrice;
    }

    public void setOriPrice(String oriPrice) {
        this.oriPrice = oriPrice;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImgSrc() {
        return this.imgSrc;
    }

    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc;
    }

    public String getSaleDesc() {
        return saleDesc;
    }

    public void setSaleDesc(String saleDesc) {
        this.saleDesc = saleDesc;
    }

    public List<ProductImg> getImgDetails() {
        return imgDetails;
    }

    public void setImgDetails(List<ProductImg> imgDetails) {
        this.imgDetails = imgDetails;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", titleId=" + titleId +
                ", name='" + name + '\'' +
                ", curPrice='" + curPrice + '\'' +
                ", oriPrice='" + oriPrice + '\'' +
                ", description='" + description + '\'' +
                ", imgSrc='" + imgSrc + '\'' +
                ", saleDesc='" + saleDesc + '\'' +
                '}';
    }
}