package com.ppx.mall.bean;

import lombok.Data;

/**
 * product_promo
 * 
 * @author bianj
 * @version 1.0.0 2021-10-06
 */
@Data
public class ProductPromo implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7073042054074171393L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Integer id;

    private Integer titleId;

    private Long productId;

    private String imgSrc;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */


    /* This code was generated by TableGo tools, mark 2 end. */
}