package com.ppx.mall.bean;

/**
 * product_img
 * 
 * @author bianj
 * @version 1.0.0 2021-11-13
 */
public class ProductImg implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -904053032705217621L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Long id;

    private Long productId;

    private String src;


    public ProductImg(Long id,Long productId, String src) {
        this.id=id;
        this.productId = productId;
        this.src = src;
    }

    public ProductImg() {
    }
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return this.productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getSrc() {
        return this.src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "ProductImg{" +
                "id=" + id +
                ", productId=" + productId +
                ", src='" + src + '\'' +
                '}';
    }
}