package com.ppx.mall.bean;

import java.util.Date;

/**
 * productorder
 * 
 * @author bianj
 * @version 1.0.0 2021-11-10
 */
public class ProductOrder implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7483945264761689791L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Long id;

    private Date createTime;

    private String userId;

    private Long productId;

    private Double price;

    private String address;

    private String telephone;

    private String name;

    public ProductOrder(Long id, Date createTime, String userId, Long productId, Double price, String address, String telephone, String name) {
        this.id = id;
        this.createTime = createTime;
        this.userId = userId;
        this.productId = productId;
        this.price = price;
        this.address = address;
        this.telephone = telephone;
        this.name = name;
    }

    public ProductOrder() {
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getProductId() {
        return this.productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "Productorder{" +
                "id=" + id +
                ", createTime=" + createTime +
                ", userId='" + userId + '\'' +
                ", productId=" + productId +
                ", price=" + price +
                ", address='" + address + '\'' +
                ", telephone='" + telephone + '\'' +
                ", name='" + name + '\'' +
                '}';
    }
}