package com.ppx.mall.bean;

/**
 * thumb
 * 
 * @author bianj
 * @version 1.0.0 2021-11-29
 */
public class Thumb implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2988013042325667413L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Long id;

    private String userId;

    private Long commentId;

    public Thumb(Long id, String userId, Long commentId) {
        this.id = id;
        this.userId = userId;
        this.commentId = commentId;
    }

    public Thumb() {
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getCommentId() {
        return this.commentId;
    }

    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "Thumb{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", commentId=" + commentId +
                '}';
    }
}