package com.ppx.mall.bean;

/**
 * user
 * 
 * @author bianj
 * @version 1.0.0 2021-10-19
 */
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -1935551200014940079L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private String account;  //账号

    private String password;//密码

    private String userName;//昵称

    private String avatarSrc;//头像地址

    private String address;//收货地址

    private String telephone;//电话号码

    private String name;//真实姓名

    public User(String account, String password, String userName, String avatarSrc, String address, String telephone, String name) {
        this.account = account;
        this.password = password;
        this.userName = userName;
        this.avatarSrc = avatarSrc;
        this.address = address;
        this.telephone = telephone;
        this.name = name;
    }

    public User() {
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getAvatarSrc() {
        return this.avatarSrc;
    }

    public void setAvatarSrc(String avatarSrc) {
        this.avatarSrc = avatarSrc;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "User{" +
                "account='" + account + '\'' +
                ", password='" + password + '\'' +
                ", userName='" + userName + '\'' +
                ", avatarSrc='" + avatarSrc + '\'' +
                ", address='" + address + '\'' +
                ", telephone='" + telephone + '\'' +
                ", name='" + name + '\'' +
                '}';
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}